/* DROP TABLE IF EXISTS QUESTION; */

CREATE TABLE IF NOT EXISTS QUESTION(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL ,
    email VARCHAR(50) NOT NULL ,
    address VARCHAR(150) NOT NULL ,
    language_from VARCHAR(20) NOT NULL ,
    language_to VARCHAR(20) NOT NULL ,
    question VARCHAR(300) DEFAULT NULL,
    status INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS USER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) NOT NULL ,
    password VARCHAR(350) NOT NULL
);