###
POST http://localhost:8090/event/create?title=title1&description=description1

### api endpoint
POST http://localhost:8090/api/v1/quote

Content-Type: application/json
{
"title" : "abc".
"description" : "abcd"
}

### # curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"title":"value", "description":"desc1"}' http://localhost:8090/api/v1/quote
POST http://localhost:8090/api/v1/quote
Accept: application/json
Content-Type: application/json

{
  "title": "value",
  "description": "desc1"
}


### api endpoint
GET http://localhost:8090/api/v1/quote



###
GET http://localhost:8090/event/index

<> 2021-03-04T224853.200.json
<> 2021-03-04T224716.200.json
<> 2021-03-04T224700.200.json

###

GET http://localhost:8090/event/1

###

POST http://localhost:8090/db/create?title=title1&description=description1

<> 2021-03-04T224827.200.txt
<> 2021-03-04T224239.200.txt
<> 2021-03-04T144418.404.json

###

GET http://localhost:8090/db/index


### Authenticate

POST http://localhost:8090/api/v1/logins
Accept: application/json
Content-Type: application/json

{
  "username": "root@admin.com",
  "password": "root123"
}


### User post

POST http://localhost:8090/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNjE1NzQ5MjE2LCJpYXQiOjE2MTU3MzEyMTZ9.nvrTFKISS3jvZEumIpjMNzSGAPLbAqN_rvM8EY_C4CPtiahaNEVCGu8VSU3oTP4ipKcK7wlBmFdi-wpukSdd9w
Content-Type: application/json

{
  "email": "ali@yahoo.com",
  "password": "password"
}


### User get

GET http://localhost:8090/api/v1/users
Accept: application/json
Content-Type: application/json
